services:
  db:
    hostname: helpdesk-db-host
    image: postgres:15.0-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/helpdesk
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails server -b 0.0.0.0"

volumes:
  db-data:
